#@ load("@ytt:data", "data")
#@ if/end hasattr(data.values, "scanpolicy") and data.values.scanpolicy == "snyk":
---
apiVersion: scanning.apps.tanzu.vmware.com/v1beta1
kind: ScanPolicy
metadata:
  name: snyk-scan-policy
  namespace: #@ data.values.name
  labels:
    app.kubernetes.io/part-of: component
spec:
  regoFile: |
    package main
    notAllowedSeverities := ["Critical", "High"]
    ignoreCves := [""]
    contains(array, elem) = true {
      array[_] = elem
    } else = false { true }
    isSafe(match) {
      fails := contains(notAllowedSeverities, match.relationships[_].ratedBy.rating[_].severity)
      not fails
    }
    isSafe(match) {
      ignore := contains(ignoreCves, match.id)
      ignore
    }
    deny[msg] {
      vuln := input.vulnerabilities[_]
      ratings := vuln.relationships[_].ratedBy.rating[_].severity
      comp := vuln.relationships[_].affect.to[_]
      not isSafe(vuln)
      msg = sprintf("%s %s %s", [comp, vuln.id, ratings])
    }
