#@ load("@ytt:data", "data")
#@ if/end hasattr(data.values, "language") and data.values.language == "python":
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: developer-defined-tekton-pipeline-python
  namespace: #@ data.values.name
  labels:
    apps.tanzu.vmware.com/pipeline: "test"
    apps.tanzu.vmware.com/language: "python"
spec:
  params:
  - name: source-url
  - name: source-revision
  workspaces:
  - name: supplychain-workspace
  tasks:
  - name: test
    params:
    - name: source-url
      value: $(params.source-url)
    - name: source-revision
      value: $(params.source-revision)
    workspaces:
    - name: supplychain-workspace
      workspace: supplychain-workspace
    taskSpec:
      params:
      - name: source-url
      - name: source-revision
      workspaces:
      - name: supplychain-workspace
      steps:
        - name: test
          image: python:latest
          script: |-
            set -ex
            cd `mktemp -d`
            wget -qO- $(params.source-url) | tar xvz -m
            pytest
